import 'dart:convert';
import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../data/database/app_database.dart';
import '../data/models/perio_chart.dart' as models;

/// Generates PDF documents for dental visits.
///
/// Output structure:
///   Page 1 — SOAP note
///   Page 2 — Periodontal chart table
///   Page 3 — Medications summary
///
/// Filename convention: visit_YYYYMMDD.pdf (no PHI in filename)
class PdfGenerator {
  PdfGenerator._();

  static final _dateFmt = DateFormat('yyyy-MM-dd');
  static const _fontSize = 10.0;
  static const _headerSize = 14.0;
  static const _subHeaderSize = 12.0;

  static Future<Uint8List> generateVisitPdf({
    required Visit visit,
    SoapNote? soapNote,
    PerioChart? perioChart,
    List<models.PerioReading> perioReadings = const [],
  }) async {
    final doc = pw.Document(
      title: 'Visit ${_dateFmt.format(visit.visitDate)}',
      author: 'dental-notes',
    );

    // Page 1: SOAP Note
    if (soapNote != null) {
      doc.addPage(_soapPage(visit, soapNote));
    }

    // Page 2: Perio Chart Table
    if (perioReadings.isNotEmpty) {
      doc.addPage(_perioPage(visit, perioChart, perioReadings));
    }

    // Page 3: Medications
    if (soapNote != null) {
      final meds = _decodeMedications(soapNote.medicationChanges);
      if (meds.isNotEmpty) {
        doc.addPage(_medicationsPage(visit, meds));
      }
    }

    // Fallback: at least one page
    if (soapNote == null && perioReadings.isEmpty) {
      doc.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.letter,
          build: (ctx) => pw.Center(
            child: pw.Text(
              'Visit ${_dateFmt.format(visit.visitDate)} — '
              'no data recorded yet.',
            ),
          ),
        ),
      );
    }

    return doc.save();
  }

  /// Placeholder for preview before data is wired.
  static Future<Uint8List> generatePlaceholder() async {
    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.letter,
        build: (ctx) => pw.Center(
          child: pw.Text(
            'PDF generation — save a SOAP note to enable full export.',
            style: const pw.TextStyle(fontSize: 14),
          ),
        ),
      ),
    );
    return doc.save();
  }

  // ── Page builders ─────────────────────────────────────────────────────────

  static pw.Page _soapPage(Visit visit, SoapNote note) {
    final planToday = _decodeList(note.planToday);
    final planNextVisit = _decodeList(note.planNextVisit);
    final planInstructions = _decodeList(note.planInstructions);
    final cdtCodes = _decodeList(note.cdtCodes);

    return pw.Page(
      pageFormat: PdfPageFormat.letter,
      margin: const pw.EdgeInsets.all(40),
      build: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _header('SOAP Note — ${_dateFmt.format(visit.visitDate)}'),
          pw.SizedBox(height: 16),
          _sectionHeader('Subjective'),
          _body(note.subjective),
          pw.SizedBox(height: 10),
          _sectionHeader('Objective — Clinical'),
          _body(note.objectiveClinical),
          if (note.objectiveRadiographic != null &&
              note.objectiveRadiographic!.isNotEmpty) ...[
            pw.SizedBox(height: 6),
            _sectionHeader('Objective — Radiographic'),
            _body(note.objectiveRadiographic!),
          ],
          pw.SizedBox(height: 10),
          _sectionHeader('Assessment'),
          _body(note.assessment),
          pw.SizedBox(height: 10),
          _sectionHeader('Plan'),
          if (planToday.isNotEmpty) ...[
            _subLabel("Today's Procedures"),
            ...planToday.map(_bullet),
          ],
          if (planNextVisit.isNotEmpty) ...[
            _subLabel('Next Visit'),
            ...planNextVisit.map(_bullet),
          ],
          if (planInstructions.isNotEmpty) ...[
            _subLabel('Patient Instructions'),
            ...planInstructions.map(_bullet),
          ],
          if (cdtCodes.isNotEmpty) ...[
            pw.SizedBox(height: 6),
            _subLabel('CDT Codes'),
            ...cdtCodes.map(_bullet),
          ],
          pw.Spacer(),
          pw.Divider(),
          pw.Text(
            'Generated by dental-notes. '
            'This document may contain clinical information.',
            style: pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey600,
              fontStyle: pw.FontStyle.italic,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Page _perioPage(
    Visit visit,
    PerioChart? chart,
    List<models.PerioReading> readings,
  ) {
    return pw.Page(
      pageFormat: PdfPageFormat.letter.landscape,
      margin: const pw.EdgeInsets.all(30),
      build: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _header('Periodontal Chart — ${_dateFmt.format(visit.visitDate)}'),
          if (chart != null)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 8),
              child: pw.Text(
                'AAP Stage ${chart.aapStage ?? "—"} / '
                'Grade ${chart.aapGrade ?? "—"} | '
                'BOP ${((chart.bopPercent ?? 0) * 100).toStringAsFixed(0)}%',
                style: pw.TextStyle(
                    fontSize: _subHeaderSize, fontWeight: pw.FontWeight.bold,),
              ),
            ),
          pw.SizedBox(height: 8),
          _perioTable(readings),
        ],
      ),
    );
  }

  static pw.Widget _perioTable(List<models.PerioReading> readings) {
    // Group readings by tooth
    final byTooth = <int, Map<String, models.PerioReading>>{};
    for (final r in readings) {
      byTooth.putIfAbsent(r.toothNumber, () => {});
      byTooth[r.toothNumber]![r.surface] = r;
    }

    final teeth = byTooth.keys.toList()..sort();

    final headers = [
      'Tooth',
      'Buccal MB',
      'Buccal B',
      'Buccal DB',
      'BOP(B)',
      'Rec(B)',
      'Lingual ML',
      'Lingual L',
      'Lingual DL',
      'BOP(L)',
      'Rec(L)',
    ];

    final rows = teeth.map((tooth) {
      final b = byTooth[tooth]?['buccal'];
      final l = byTooth[tooth]?['lingual'];
      return [
        '#$tooth',
        '${b?.depthMb ?? "—"}',
        '${b?.depthB ?? "—"}',
        '${b?.depthDb ?? "—"}',
        b?.bop == true ? 'Y' : '',
        '${b?.recession ?? ""}',
        '${l?.depthMb ?? "—"}',
        '${l?.depthB ?? "—"}',
        '${l?.depthDb ?? "—"}',
        l?.bop == true ? 'Y' : '',
        '${l?.recession ?? ""}',
      ];
    }).toList();

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: rows,
      cellStyle: const pw.TextStyle(fontSize: 8),
      headerStyle: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
      cellAlignment: pw.Alignment.center,
      headerDecoration:
          const pw.BoxDecoration(color: PdfColors.grey200),
      cellPadding: const pw.EdgeInsets.all(3),
    );
  }

  static pw.Page _medicationsPage(
    Visit visit,
    List<Map<String, dynamic>> meds,
  ) {
    return pw.Page(
      pageFormat: PdfPageFormat.letter,
      margin: const pw.EdgeInsets.all(40),
      build: (ctx) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _header(
              'Medication Changes — ${_dateFmt.format(visit.visitDate)}',),
          pw.SizedBox(height: 12),
          pw.TableHelper.fromTextArray(
            headers: ['Drug', 'Dose', 'Frequency', 'Action', 'Note'],
            data: meds
                .map((m) => [
                      m['drug_name'] ?? m['drugName'] ?? '',
                      m['dose'] ?? '',
                      m['frequency'] ?? '',
                      m['change_type'] ?? m['changeType'] ?? '',
                      m['prescribing_note'] ?? m['prescribingNote'] ?? '',
                    ],)
                .toList(),
            cellStyle: const pw.TextStyle(fontSize: 9),
            headerStyle:
                pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold),
            headerDecoration:
                const pw.BoxDecoration(color: PdfColors.grey200),
            cellPadding: const pw.EdgeInsets.all(4),
          ),
        ],
      ),
    );
  }

  // ── Text helpers ──────────────────────────────────────────────────────────

  static pw.Widget _header(String text) => pw.Text(
        text,
        style: pw.TextStyle(
            fontSize: _headerSize, fontWeight: pw.FontWeight.bold,),
      );

  static pw.Widget _sectionHeader(String text) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 4),
        child: pw.Text(
          text,
          style: pw.TextStyle(
              fontSize: _subHeaderSize, fontWeight: pw.FontWeight.bold,),
        ),
      );

  static pw.Widget _subLabel(String text) => pw.Padding(
        padding: const pw.EdgeInsets.only(top: 4, bottom: 2),
        child: pw.Text(
          text,
          style: pw.TextStyle(
              fontSize: _fontSize, fontWeight: pw.FontWeight.bold,),
        ),
      );

  static pw.Widget _body(String text) => pw.Text(
        text,
        style: const pw.TextStyle(fontSize: _fontSize),
      );

  static pw.Widget _bullet(String text) => pw.Padding(
        padding: const pw.EdgeInsets.only(left: 12, bottom: 2),
        child: pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('•  ', style: const pw.TextStyle(fontSize: _fontSize)),
            pw.Expanded(
              child: pw.Text(text,
                  style: const pw.TextStyle(fontSize: _fontSize),),
            ),
          ],
        ),
      );

  // ── JSON helpers ──────────────────────────────────────────────────────────

  static List<String> _decodeList(dynamic value) {
    if (value is String) {
      try {
        return (jsonDecode(value) as List).cast<String>();
      } catch (_) {
        return [];
      }
    }
    return [];
  }

  static List<Map<String, dynamic>> _decodeMedications(dynamic value) {
    if (value is String) {
      try {
        return (jsonDecode(value) as List).cast<Map<String, dynamic>>();
      } catch (_) {
        return [];
      }
    }
    return [];
  }
}
